name: My first Github Pipeline

on: [push]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8,3.9]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Env
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        
      - name: Run Tests
        run: |
          cd src
          python -m pytest addn.py
